### ISSUE TITLE
add on page search to policies page (with js)

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/theyvoteforyou#1000]
This would enable users to quickly filter the policies list to find ones they are interested in. It can be quite difficult to scroll through the very long list of policies and pinpoint one of interest. A simple search form that filtered results (based on title initially) would make it more useable.

People are making searches from the policies page through the site search:

![screen shot 2014-12-03 at 11 08 07 am](https://cloud.githubusercontent.com/assets/1239550/5273535/bf0d51d6-7adc-11e4-85b0-a055f909f960.png)

**Comment by mlandauer** [comment]
Yes to this a hundred fold! We have a lot of policies and this is the quickest way we could make that page more easy to use
