### ISSUE TITLE
add the subscriber count to policy update emails

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/theyvoteforyou#1054]
**User story:** As a contributor, when someone updates a policy that I subscribe to, I want to know how many others are subscribed, so that I am aware of the potential audience/collaborators who will be notified of contributions I make, which encourages me to contribute.

Letting people know how many other people received the notice is a simple way to re-enforces connections between contributors—it reminds them that they aren't alone in there interest.

We could add to the email: 'This policy has 15 subscribers'. Like:

> **For removing children from immigration detention**
> 
> Changed text on related division Motions — To not Commend or Support the Australian Human Rights Commission
> 
> Alex Jewson 12:05AM - 11 Mar 2015
> 
> This policy has 6 subscribers
> 
> Visit the policy page to unsubscribe from this policy.
> 
> View all your subscriptions.

Like [PlanningAlerts](https://www.planningalerts.org.au/applications/500133) tells you how many people were notified of a DA:

> 71 people were notified of this application via email alerts

**Comment by Tanuja-Sawant** [comment]
@equivalentideas may I take this up?

**Comment by mlandauer** [comment]
I like this. Let's do it
