### ISSUE TITLE
Filter policies based on category on an MP's page

### ISSUE THREAD

**Issue by henare** [openaustralia/theyvoteforyou#1074]
On #1069 @equivalentideas says that most people that use the site go to their MP's page. On that page we currently list policies by agreement. The list is already pretty big and it'll only get bigger as more policies are added.

To help people to find policies they're interested in we could put buttons at the top of that list that filter based on the policy's category, e.g. Health, Education, etc.

**Comment by equivalentideas** [comment]
Here's the user story statement that relates to this from #1069 :

> As someone interested in education, when trying to see how my MP voted on policies related to education, it’s difficult for me to see how they vote on policies related to education, because they’re split across the entire voting record list. Some are at the top of the page, some are much further down. I have to pay close attention and slowly read the whole list to spot the policies that matter to me.

> For this person it could be really helpful to have all the policies they're interested in grouped together.
