### ISSUE TITLE
Missing division - 3 Dec 2015, Senate, 22:38

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1080]
The third reading division for _Australian Citizenship Amendment (Allegiance to Australia) Bill 2015_ is not up on TVFY (see it on the [Hansard](http://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;db=CHAMBER;id=chamber%2Fhansards%2F63c5a341-7e3b-44d6-a47f-f31da7eb5049%2F0298;query=Id%3A%22chamber%2Fhansards%2F63c5a341-7e3b-44d6-a47f-f31da7eb5049%2F0000%22))

**Comment by MicaelaMicaela** [comment]
Actually, an earlier In Committee division is missing too - same bill, 3 Dec 2015, Senate, 22:04 (see it on the [Hansard](http://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;db=CHAMBER;id=chamber%2Fhansards%2F63c5a341-7e3b-44d6-a47f-f31da7eb5049%2F0279;query=Id%3A%22chamber%2Fhansards%2F63c5a341-7e3b-44d6-a47f-f31da7eb5049%2F0000%22))

**Comment by henare** [comment]
My guess would be that because it was late in the evening it wasn't in the Hansard we initially scraped.
