### ISSUE TITLE
Some senators who've changed parties are friends with themselves

### ISSUE THREAD

**Issue by nickjevershed** [openaustralia/theyvoteforyou#1082]
Noticed some odd behaviour with some senators that have switched parties, eg. Jacqui Lambie has herself (whilst Palmer United Party) as a possible friend on this page with 50% agreement
[https://theyvoteforyou.org.au/people/senate/tasmania/jacqui_lambie/friends](https://theyvoteforyou.org.au/people/senate/tasmania/jacqui_lambie/friends)

And John Madigan has himself as a possible friend on this page with a similar issue:
[https://theyvoteforyou.org.au/people/senate/victoria/john_madigan/friends](https://theyvoteforyou.org.au/people/senate/victoria/john_madigan/friends)

However it's not an issue for Glen Lazarus, who also switched parties. 

[https://theyvoteforyou.org.au/people/senate/queensland/glenn_lazarus/friends](https://theyvoteforyou.org.au/people/senate/queensland/glenn_lazarus/friends)

**Comment by equivalentideas** [comment]
Thanks @nickjevershed :bear: this could well be related to the problem of duplicate members https://github.com/openaustralia/publicwhip/issues/1068

**Comment by equivalentideas** [comment]
In fact I'd call it a duplicate. I'll close #1068 even though it's older because I think you're done a good job with the title and evidence here :star:

**Comment by nickjevershed** [comment]
No worries!

**Comment by mlandauer** [comment]
This will probably be fixed by implementing #299

**Comment by mlandauer** [comment]
This was indeed (as expected) fixed by #299
