### ISSUE TITLE
Make the policy description more obvious and clearer on the *MP Votes on Policy* page

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/theyvoteforyou#1085]
This comes from an issue reported on openaustralia.org.au https://github.com/openaustralia/openaustralia/issues/590 .

On the [openaustralia.org.au MP pages](http://www.openaustralia.org.au/mp/anthony_albanese/grayndler), and also on the [MP pages on They Vote For You](https://theyvoteforyou.org.au/people/representatives/grayndler/anthony_albanese) we link from the MPs voting record to their votes on a policy.

On this page it's useful to know a little more about what the policy means than just it's title.

We currently provide the policy description, but it's not very obvious. In fact [I missed it when I was looking for it](https://github.com/openaustralia/openaustralia/issues/590#issuecomment-197073975)

![screen shot 2016-03-16 at 11 02 58 am](https://cloud.githubusercontent.com/assets/1239550/13798147/74fd387a-eb67-11e5-8519-2effad399a1c.png)

We could use the design pattern from the Policy#show page to make the description more prominent?

![screen shot 2016-03-16 at 11 28 14 am](https://cloud.githubusercontent.com/assets/1239550/13798448/9e31a336-eb6a-11e5-804a-8019169d1c3a.png)

**Comment by brtrx** [comment]
Below are two options for improving the readability of this page.
Before I discuss them, though, it's worth pointing out the misalignment of elements, which is worth fixing, regardless of whether these options are adopted.
![image](https://cloud.githubusercontent.com/assets/8436356/13806284/fbbc7fc2-eb5a-11e5-96e5-08642240304f.png)

# Option 1: Minimum change
This option uses the formatting on the public#show page, but makes this a link for natural cross-reference to the policy and other member's voting records.
![image](https://cloud.githubusercontent.com/assets/8436356/13806288/08293db8-eb5b-11e5-863e-ee00f8bc923c.png)

# Option 2: Visualise and explain the position expressed in the header
While reviewing this page, it became clear to me that this page actually provides a voting record to explain and justify the political position expressed in the header (e.g. Very Strongly For).
With that in mind, I designed this option with the aim of explaining the header (i.e. to answer the question "Why do you think this member is very strong for this policy?").
I've tried to format information to that explanation can be read in the form of a single sentence which explains both the policy and the member's position. 
However, it also quickly became clear that the latter requires introducing the concept of agreement score, and from there I moved to a design that included a graphical representation of that score. The words "agreement score" in the first line should be anchor-linked to the (excellent) **How "voted very strongly for" is worked out** section below.  
The strength of this design lies in providing sufficient information to justify the header, without the visitor having to grok the entire table of votes, if they don't require that much detail.
![image](https://cloud.githubusercontent.com/assets/8436356/13806586/c957c5b2-eb5c-11e5-86ec-29b8f5adc8e9.png)

**Comment by equivalentideas** [comment]
> Before I discuss them, though, it's worth pointing out the misalignment of elements, which is worth fixing, regardless of whether these options are adopted.

Thanks @brtrx . I can see that issue in a few places across the site. Would you be interested in submitting a Pull Request to fix it?

> Below are two options for improving the readability of this page.

I think the minimal option is more closely focused on this issue, but I think the idea behind the second option is interesting too. Option two also contains option one. I think option two could be related to a new issue about making the relationship between the stated position and the votes clearer.

Option one also makes me wonder if we could make it more similar to the policy page layout, but with the MPs name and position above the policy title? Then you could have the text relating to the specific MPs above the list of divisions. Something like “There have been 5 divisions on this issue since Anthony Albanese joined Parliament. They have strongly for ... .” What do you think of that idea @brtrx ?

**Comment by brtrx** [comment]
Thanks @equivalentideas 

1. I'd be happy to submit a Pull Request for better vertical alignment, but not sure how to do this, without having code committed somewhere? (Excuse my noob question, github asks me to start by comparing branches) Shall I just create an issue, instead?
2. I'll create a separate issue for making the relationship between stated position and the votes clearer.
3. I'm all for including the persons party and electorate/state here. As I mentioned in #1092, there's too many clicks to get that information from a policy index page listing.

**Comment by equivalentideas** [comment]
> I'd be happy to submit a Pull Request for better vertical alignment, but not sure how to do this, without having code committed somewhere? (Excuse my noob question, github asks me to start by comparing branches)

No such thing as noobs questions round here :wink: Have you used Git for collaboration like this before?

> I'll create a separate issue for making the relationship between stated position and the votes clearer.

:+1: 

> I'm all for including the persons party and electorate/state here. As I mentioned in #1092, there's too many clicks to get that information from a policy index page listing.

As with #1092 : What's the user need?

**Comment by brtrx** [comment]
I've used Git as a code repository for an overly ambitious personal project to learn a little node.js. I tried to write something to automatically build Spotify playlists of Rage track listings... without understanding asynchronous programming at all really. :clap: 
Otherwise, I've used JIRA a lot for collaboration - never participated in a shared repo like this.

So, focusing on Option 1 for the moment (considerations in Option 2 separated into #1094.
Here's a possible revision, including your suggestion on wording, and for a position to be included above the line (though I'm tempted to call that a different issue, too) 

![option 3 min change with person info](https://cloud.githubusercontent.com/assets/8436356/13959141/1d39a286-f053-11e5-983d-6019aecc118a.png)

**Comment by equivalentideas** [comment]
> I've used Git as a code repository for an overly ambitious personal project to learn a little node.js.

Here's some explanation I've found useful on contributing via PRs: https://help.github.com/articles/using-pull-requests/ and https://github.com/blog/1943-how-to-write-the-perfect-pull-request .

I think maybe try and find a really tiny bug on a project and try fixing it and submitting a PR before attempting something fairly major like this.

**Comment by brtrx** [comment]
Thanks, but I think we're talking at cross-purposes. I don't feel competent to do any coding. Perhaps the appropriate response to your question "Would you be interested in submitting a Pull Request to fix it?" should've just been no. Sorry I can't contribute that way. I know that's usually the most limited resource. Let me know if you're looking for more developers, and I'll put the word out.
