### ISSUE TITLE
Add names to the list of people on the policy page, so I don't need to recognize their faces to identify then

### ISSUE THREAD

**Issue by brtrx** [openaustralia/theyvoteforyou#1090]
These could be added a links below each profile image.

The mock up below uses this page as a template:
https://theyvoteforyou.org.au/policies/47

![image](https://cloud.githubusercontent.com/assets/8436356/13911114/71b94d84-ef2c-11e5-98b0-cea2915717dd.png)

This will have the added benefit of clarifying that the ordering of members within a specific level of agreement is _alphabetical_ (and not, for example, an indication of relatively stronger or weaker agreement with a policy). For example, Albanese is first because his name starts with A, and not because he's the strongest supporter of an NBN (using fibre to the premises).

**Comment by kategolden** [comment]
I concur and would suggest adding district name + full names together, for those who may not know who their MPs are

**Comment by brtrx** [comment]
I tried a version with just that, and it got too cluttered.
They are one click away from that member's details, which isn't too bad.
But, in the case where someone's looking for someone from their electorate, my recommendation is to add a live text filter that filters on name and electorate (and potentially also postcode). See #1091

**Comment by katska** [comment]
how about being able to flip from images to listed by names?

**Comment by mlandauer** [comment]
> how about being able to flip from images to listed by names?

This idea initially didn't appeal to me but I've come around. Here's why:

The only way we could reliably fit the person's name alongside (or under) the photo is if we just use their last name. This is a perfectly reasonable approach but one that actually is different then everywhere else we use MPs names. Everywhere (as far as I'm aware) on openaustralia.org.au and theyvoteforyou.org.au we use people's full name (e.g. Wendy Askew). This is a very conscious decision to keep the names informal and relatable. After all politicians are people, just like us, and we should remember that. By just using a last name we risk a weird kind of objectification I think. 

So, I think being able to switch to a list of names is a reasonable workaround. It's not great but I think the alternative is marginally worse for very different reasons.
