### ISSUE TITLE
When I'm looking at a policy I'm interested in, help me see how my MP voted on it when I don't know their name or face

### ISSUE THREAD

**Issue by brtrx** [openaustralia/theyvoteforyou#1091]
A mock up of the proposed positioning and default state of the text filter is below.

Note, though not a technical required, this change has a UX dependence on #1090 (Add names to the list...), because otherwise the effect of the filter on the list won't be immediately apparent. 
### Layout

![or text filter](https://cloud.githubusercontent.com/assets/8436356/13911361/b875e93c-ef2f-11e5-9137-b4de2f4ebe5c.png)
### Behaviour
- No min number of chars (though less is better, if required for performance)
- Groupings that are empty after filtering should be hidden
- Filter should match based on **first name** or **last name** or **electorate**, and can be set to match from start of word (rather than anywhere within these fields) if performance requires
### Results Layout

![option 1b filter result](https://cloud.githubusercontent.com/assets/8436356/13911568/829b970a-ef32-11e5-88f7-76bce176ac4b.png)

**Comment by henare** [comment]
Postcode would be good too so you can find your representative without needing to know who they are or what your electorate is called.

**Comment by equivalentideas** [comment]
Changed the name of this issue to describe things from the users perspective rather than a solution. I think it frames the discussion better. I do like the solution though ;-)
