### ISSUE TITLE
Add a summary of groupings, with anchor links and a bar graph visualisation, so I can quickly asses relative support for a policy

### ISSUE THREAD

**Issue by brtrx** [openaustralia/theyvoteforyou#1093]
### Rationale

If a visitor wishes to assess relative support for a policy, they currently need to scan the entire page (which can be very long), or sometime even count the number of profile photos in each support grouping.

This change attempts to better support this assessment by offering a summary of the level of support for or against a position. The bar graph layout is here to support users with a preference for visual learning styles.

Each summary line is an anchor link to the grouping, to allow users to quickly jump to a controversial or interesting group.
### Layout

![option 3c category filter and summary](https://cloud.githubusercontent.com/assets/8436356/13912556/9bca3afe-ef3e-11e5-90cb-25d6f9b051a9.png)
### Notes
- The layout above includes features from #1090 (Add names...), #1091 (live text filter) and #1092 (party & house filters), but these aren't dependencies (a clean version is below)
- At small screen widths, each bar should ideally wrap underneath the relevant anchor link as shown below
  ![option 3c summary - desktop vs mobile layouts](https://cloud.githubusercontent.com/assets/8436356/13912668/ef75226c-ef3f-11e5-9803-874fb1631c40.png)
#### MVP

This "clean" version below shows the concept without features covered in other issues.

![option 2c summary no cat filter](https://cloud.githubusercontent.com/assets/8436356/13912568/ba95ccd2-ef3e-11e5-87fd-6413f152f8bd.png)

Note, however, the change to the divisions anchor link ("4 divisions"), which has been reduced in size and changed in text. IMO it should have the same prominence as the summary links (reviewing particular divisions is quite an advanced step in reviewing a policy)

**Comment by equivalentideas** [comment]
Nice one @brtrx , I think something like this could definitely be useful in adding more context to the page. I do think we could refine it to something simpler though.

I'm reminded of the quite abstract stacked chart that Github use to show the different languages in a repo:

![screen shot 2016-03-22 at 8 49 50 am](https://cloud.githubusercontent.com/assets/1239550/13935410/48d88a94-f00b-11e5-8bde-7cc46f6710c6.png)
![screen shot 2016-03-22 at 8 52 10 am](https://cloud.githubusercontent.com/assets/1239550/13935444/6ff505a8-f00b-11e5-858b-a5e186f32e6d.png)

I actually find that pretty useless on Github, but it does add a little variety and visual interest to the page.

Could something similar be used around the header to give you a quick sense of people's voting records on the policy? You could tell quickly if the parliament was generally against something, for it, or it was very close. You could keep all the linking behaviour too.

**Comment by brtrx** [comment]
I did try exactly that pattern in a version of the wireframe. It saves vertical height (arguably not a finite resource) at the expense of ease of understanding.

I found that - as with the Github feature - it was quite difficult to work out what each colour indicated without any supporting text, and there wasn't room for text descriptions when the % in any group was small.

Finally, because of party whips, there's a lot of block voting, so there tends to be two large groups close to 50% and a few small groups <10%. In that case, the key quick comparison is the large groups, which the vertical layout I've used makes easier to see. 

With that in mind, here's are three variations of the summary panel, making it easier to compare the total for/against.

![option 2d - summary - better comparison](https://cloud.githubusercontent.com/assets/8436356/14722948/c9fbc03a-080e-11e6-8e36-84559ecd3ad7.png)

![option 2e - summary - better comparison](https://cloud.githubusercontent.com/assets/8436356/14722953/d31b8f10-080e-11e6-80dc-3dec5c9aeebd.png)

![option 2f - summary - better comparison](https://cloud.githubusercontent.com/assets/8436356/14722960/d89236d8-080e-11e6-969d-25981bd0bebc.png)

![option 2g - summary - better comparison](https://cloud.githubusercontent.com/assets/8436356/14723047/5797bc82-080f-11e6-89af-b70ba658cec0.png)

My preference is for an option that shows more detail about the totals in each group, and provides includes anchor links to the page section, but let me know what you think.

**Comment by equivalentideas** [comment]
Great discussion and ideas on here. I'm personally not sure about this concept:

> If a visitor wishes to assess relative support for a policy

I don't really see that as a priority need for most users that would justify adding such a significant element to the page. I think most people want to find out how their MP voted, which isn't that easy right now.

I think a more effective feature would be a way to filter the list of MP name or electorate, like @brtrx suggested above—but I'd say this would be pushed up in the visual hierarchy significantly.

![screen shot 2017-11-21 at 11 39 46 am](https://user-images.githubusercontent.com/1239550/33048799-da1b38dc-ceb0-11e7-85a2-d574d2306021.png)

Maybe replacing the divisions count/link, which could sit on the righthand side on wide screens:

![screen shot 2017-11-21 at 11 42 01 am](https://user-images.githubusercontent.com/1239550/33048857-26a12f7c-ceb1-11e7-9f66-06415228ac28.png)

One thing to consider when implementing the search there is what will people take 'electorate' to mean. If I searched 'NSW' would I expect to just see NSW Senators, or all MPs for electorates that are in the state, like 'Sydney'.

I'd suggest closing this issuing and making a new issue for that feature.

**Comment by cofiem** [comment]
If finding a particular MP, or group of MPs, is the most common goal, then yes I agree, this summary doesn't add much.

However, there currently isn't any indication of the overall support/opposition to a policy. For me, in addition to finding out how my MP vote, I also want to see where the policy is at e.g. is there majority support?

I suppose a quick scroll gives a similar overview to the chart. Perhaps going with the party/indep. support/opposition idea rather than just vote counts provides more useful information? The very strong/strong/moderate bars could be changed out for party groupings, with the same For/Against/Mixed/Never sets? That would give an excellent overview of who supports/opposes/doesn't care about the policy.
