### ISSUE TITLE
Make the relationship between stated position and the votes clearer on the *MP Votes on Policy* page

### ISSUE THREAD

**Issue by brtrx** [openaustralia/theyvoteforyou#1094]
As mentioned in #1085, it may be possible to help users more quickly understand the way TWFY comes to the conclusion that someone votes "very strongly for" a policy.

While the explanation at the bottom of the page is really excellent, users need to overcome a few barriers at the moment:
- a change of language (from "votes" to "divisions") at least at the top of the page
- physical separation of the explanation from what needs explaining (they need to scroll past all the divisions before they become aware that there is an explanation available)

In my suggestion in #1085, I tried to bring the agreement score higher up the page, and use that as an anchor link to the explanation. I can see though that while this score explains the logic behind the stated position, it may give a false sense of accuracy. After all, that score is only as good as the identification of divisions as belonging to a policy or as being relatively important votes.

Not sure how to solve this one, but as @equivalentideas pointed out, it's worth separating out into its own issue.

**Comment by equivalentideas** [comment]
Thanks @brtrx this is a good explanation of the issue :+1:

**Comment by mlandauer** [comment]
Related to #1271
