### ISSUE TITLE
When we don't have an image for a member, show something better than text “Photo of <name>”

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/theyvoteforyou#1107]
This looks really sloppy:

![screen shot 2016-09-01 at 5 24 09 pm](https://cloud.githubusercontent.com/assets/1239550/18158903/7715d75c-7069-11e6-854d-09354f72d012.png)

**Comment by Taz17** [comment]
What would the solution of this issue look like? Even after updating the members images there might be members without an image.

Example: [](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=286349)[Senator Greg Mirabella](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=286349) does not have an image.

See [senator images](https://www.aph.gov.au/Senators_and_Members/Senators/Senators_photos) and [member images](https://www.aph.gov.au/Senators_and_Members/Members/Members_Photos) here.

Some good news, its only Senator Greg Mirabella that does not have a photo. All other members and senators do.

**Comment by mlandauer** [comment]
The idea would be to use some kind of generic gender neutral image if there isn't an existing photo. An example of the kind of thing would be https://thenounproject.com/icon/user-3692903
![noun-user-3692903](https://user-images.githubusercontent.com/2221/153340609-056ce441-989b-486a-8382-cf85ddc83087.svg)
It would obviously need to be scaled down and made a lighter colour so it doesn't completely dominate any other image

**Comment by katska** [comment]
More like this?
<img width="98" alt="Screen Shot 2022-08-17 at 10 42 00 am" src="https://user-images.githubusercontent.com/1001129/185009050-0391f0ec-a4a5-4f5e-8ed3-b94e2b550488.png">

Could have different coloured backgrounds as per senate (red) and house of reps (green) photos also.

**Comment by mackaymackay** [comment]
@katska I think having green/red backgrounds could be helpful, as it would match what parliament already tends to do with their photos (using the red or green background for the senators or MPs respectively)

While looking at this, I just noticed that we don't seem to have people without photos showing up on the general policy pages at all anymore.

e.g. on his voting card, Stephen Bates is listed as [voting consistently for net zero emissions](https://theyvoteforyou.org.au/people/representatives/brisbane/stephen_bates/policies/285), but he doesn't appear on the [actual policy page](https://theyvoteforyou.org.au/policies/285)

![image](https://user-images.githubusercontent.com/6345406/185504362-2edd8a86-2a33-478b-a4be-1163235c0164.png)

**Comment by katska** [comment]
@mackaymackay That's no good! Thanks for spotting the problem!

**Comment by mackaymackay** [comment]
I'm reopening this issue, as it seems to be related to https://github.com/openaustralia/theyvoteforyou/issues/1443 (as mentioned above)
