### ISSUE TITLE
Explanation of what "attendence figures mean" is very unclear

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/theyvoteforyou#1156]
See https://theyvoteforyou.org.au/help/faq#attendance

It currently says:

> ## What do the "attendance" figures mean?
> 
> "Attendance" figures record the politicians who vote in any given division.

I don't think I would understand what's intended if I read this. This should be in simple plain English. It currently doesn't meet our [design principles](https://github.com/openaustralia/publicwhip/blob/master/design_docs/principles.md) or match the [project’s voice](https://github.com/openaustralia/publicwhip/blob/master/design_docs/design_persona.md#voice).

**Comment by katska** [comment]
@mlandauer could you be more specific about what could be simpler?
