### ISSUE TITLE
Consistently use term 'summary' not 'description' on Division history page

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/theyvoteforyou#1157]
On the Division show and edit pages we use 'summary' to describe the text explaining the division that people edit:

![screen shot 2017-05-16 at 5 08 51 pm](https://cloud.githubusercontent.com/assets/1239550/26093781/a15d0768-3a5a-11e7-8295-336c78e51b62.png)
![screen shot 2017-05-16 at 5 09 11 pm](https://cloud.githubusercontent.com/assets/1239550/26093782/a1f33986-3a5a-11e7-8906-010f88a93373.png)
![screen shot 2017-05-16 at 5 09 54 pm](https://cloud.githubusercontent.com/assets/1239550/26093785/a393ab72-3a5a-11e7-9958-a419266f0074.png)

On the history page we use "description" in four places. These should be changed to 'summary', which sounds less databasey that 'description'.

![screen shot 2017-05-16 at 5 07 33 pm](https://cloud.githubusercontent.com/assets/1239550/26093694/4bf1d4e8-3a5a-11e7-8b3e-65ed218df413.png)

**Comment by mlandauer** [comment]
+1 for consistent language
