### ISSUE TITLE
If you enter "3672 Cathy McGowan" in search, you get "No results found"

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/theyvoteforyou#1163]
See https://theyvoteforyou.org.au/search?query=3672+Cathy+McGowan&button=hero_search

We were contacted by someone who was trying to find their rep after someone sent them a link to the home page via FaceBook Message:

> I couldn't find how my Rep voted by entering 3672 Cathy McGowan  Had to go searching her by name
> Does the website need a tweak?

> I entered 3672 Cathy McGowan on the only line offered

This is a very reasonable search to make and should take them to the page for their MP https://theyvoteforyou.org.au/people/representatives/indi/cathy_mcgowan

**Comment by mlandauer** [comment]
In the code https://github.com/openaustralia/publicwhip/blob/master/app/controllers/home_controller.rb#L17 you can see we're just looking for 4 numbers at the start of the search and that just kicks in specialised postcode search code. Fixing this issue looks pretty straightforward. We could either:
1. not treat a search that included extra text as in "3672 Cathy McGowan" as a special case or
2. we could try the postcode search and if that doesn't return any result we try the regular search

Option 2 feels like the one that would be the most robust
