### ISSUE TITLE
policies.json in API should report last updated timestamp

### ISSUE THREAD

**Issue by jnothman** [openaustralia/theyvoteforyou#1164]
Large parts of the tvfy data are static. Policies, however, can be changed. If a last-updated timestamp was provided for each policy in the API (presumably the max over `policies.updated_at` and any corresponding `policy_divisions.updated_at`), and particularly in the overview, this would make it much easier for users to capture changes incrementally, rather than download all the data.

**Comment by henare** [comment]
We already display the last edit time on the policies index page: https://theyvoteforyou.org.au/policies

Adding this to the API seems like a good idea and it should be very straightforward :+1:

**Comment by kevinjcliao** [comment]
Hi there! Found this project and am giving this a shot. How do I disable the requirement for an API key when I'm developing locally?

**Comment by kevinjcliao** [comment]
I just disabled the require_key in the applicationcontroller for the API for now. I'll revert it when I commit.

**Comment by mlandauer** [comment]
Seems like a sensible and straightforward addition
