### ISSUE TITLE
Senators' votes being recorded twice thanks to being listed in two different parties

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1190]
We've had a user point out that certain senators' votes are being recorded twice in divisions as they have two entries. For example, in [this division](https://theyvoteforyou.org.au/divisions/senate/2018-11-12/5), Fraser Anning is listed once as an independent (correct) and once as part of the Katter Party (incorrect). And in [this division](https://theyvoteforyou.org.au/divisions/senate/2018-08-16/2), two senators are listed as part of both the Centre Alliance (correct) and Nick Xenophon's Party (incorrect - party no longer exists).

I've check the [senator list](https://github.com/openaustralia/openaustralia-parser/blob/master/data/senators.csv) and the dates there don't overlap, so it's not a data entry issue. I also checked the Hansard to see if their data is similarly doubling up senators (which isn't so unlikely considering how much movement has been going on in our Parliament), but no, looks like it's just us.

I'm not sure how many divisions are affected, but it's something I'll keep an eye out for from now on.

**Comment by MicaelaMicaela** [comment]
Julia Banks is also showing up twice - as still part of Liberal Party *and* Independent in December (she changed party 27.11.2018), e.g. in [this division](https://theyvoteforyou.org.au/divisions/representatives/2018-12-06/3)

**Comment by jamezpolley** [comment]
Part of what's happening in #1108 is an example of this problem - Nick Xenophon had a stint as an independent and a stint in NXT

(The other part of #1108 is that the dates we have for Nick are wrong; that's being fixed elsewhere)

**Comment by MicaelaMicaela** [comment]
Just noticed this also happening with Senator Brian Burston, who used to be in One Nation and is now in United Aus Party. On at least [one occasion](https://theyvoteforyou.org.au/divisions/senate/2018-10-18/4) he shows as a rebel from Hanson's Party and, strangely enough, absent from the UAP. Actually, he shows up as absent from one party while present for the other [more than once](https://theyvoteforyou.org.au/divisions/senate/2018-10-18/5).

**Comment by mlandauer** [comment]
Oops. Pressed the wrong button! :-(
