### ISSUE TITLE
Please list members contact details

### ISSUE THREAD

**Issue by storyjesse** [openaustralia/theyvoteforyou#1191]
This is such a fantastic site! But PLEASE include a link to politicians contact details on their profile page. e.g. Just above or below "Speeches in Parliament"

I'd also love to see this site extended to include state politicians as well. I've just spent about an hour searching and can't find any site that allows me to search for BOTH my state and federal politicians details.

**Comment by MicaelaMicaela** [comment]
The contact link should go to the [relevant APH page](https://www.aph.gov.au/Senators_and_Members/Guidelines_for_Contacting_Senators_and_Members), as it's updated each time our MPs and Senators change (which happens a lot these days!!) and gives some useful info how to address them, for those into that sort of thing

**Comment by storyjesse** [comment]
I can just say that from first hand experience browsing theyvoteforyou, the site makes me want to contact politicians to thank them and berate them for their decisions. I think this is what the site was designed for and from personal experience the effort to find politicians' contact details myself often makes me give up and no longer have the motivation to tell them what I think. A prominant link to the [relevant APH page](https://www.aph.gov.au/Senators_and_Members/Guidelines_for_Contacting_Senators_and_Members) as [mackaymackay](https://github.com/mackaymackay) suggested would solve this issue and, I believe, greatly increase the impact the site has.
