### ISSUE TITLE
150% Attendance at division

### ISSUE THREAD

**Issue by technicallynotdeaf** [openaustralia/theyvoteforyou#1202]
In this division, it says PHON had 150% attendance:

https://theyvoteforyou.org.au/divisions/senate/2018-06-27/5

**Comment by Taz17** [comment]
@mlandauer should we use the word `attended` instead of `turnout` since we have the definition of `attendance` in the FAQ

**Comment by mlandauer** [comment]
@Taz17 could you please create a new issue for this suggestion? On the face of it it makes sense to me. Could you also look through the codebase and all the user-facing wording and see what wording is used in other places (if any)? Thank you

**Comment by Taz17** [comment]
That is now in issue #1298

**Comment by Taz17** [comment]
@mlandauer I pulled all the data i could (from 2018-06-26 to 2022-02-01). However I was not able to reproduce this bug.

**Comment by mlandauer** [comment]
> @mlandauer I pulled all the data i could (from 2018-06-26 to 2022-02-01). However I was not able to reproduce this bug.

Interesting! Now to figure out why it's happening in production then and not elsewhere

**Comment by Taz17** [comment]
There also is 3 more rows in the votes table in production.

Votes table in production:

![Production-table](https://user-images.githubusercontent.com/86769131/152260975-f19c7547-bb92-4bfd-9a7a-25f6456910cc.png)

Local votes table

![dev-table](https://user-images.githubusercontent.com/86769131/152261032-5ee6eea4-a9ab-499c-ac18-17e00e5d4e96.png)
