### ISSUE TITLE
People pages refer to "2013 (current) Parliament"

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1220]
Under the "Possible Friends" title, some people pages include the following sentence: 

> Shows which Senators voted most similarly to this one in the **2013 (current) Parliament**...

This may be connected to a closed issue from 2014 called [Divisions page calls current parliament "2013"](https://github.com/openaustralia/publicwhip/issues/140)

Screenshot from a Centre Alliance senator's page:

![image](https://user-images.githubusercontent.com/6345406/75498337-fa1bd900-5a1a-11ea-951c-c00037bcabdf.png)

**Comment by andrewcameronsims** [comment]
Hi Mackay.

Am I right in thinking that this should display the current parliament as being the 2019-current parliament? From looking at the way this is calculated in the Parliament model there is no record of the 2016-2019 (43rd) or 2019-current (44th) parliaments; they are missing.

I would be happy to open a PR to make this change if I am correct in my assumption here.

**Comment by mlandauer** [comment]
This was fixed by #299. The paragraph with the wording in question has now been updated to make no mention of a particular parliament as a person's entire voting history (even if they change party, house, etc..) is taken into account when showing "possible friends".
