### ISSUE TITLE
Directly compare the voting record of two politicians

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/theyvoteforyou#1251]
It's not immediately obvious why adding a feature to directly compare two politicians on TheyVoteForYou would be useful.

Consider this:
* I might want to make the point that two people in the same party who have quite different views actually vote almost identically. This is very compelling when you give a specific example rather than just an abstract statement that "in Australia people vote very strongly along party lines".
* Or you might be interested in comparing the voting record of an independent against a member of a major party who on the face of it has very similar views. You might discover, for instance, that despite their views being apparently similar the way they vote can be quite different!

We have an election coming up (likely early next year) and this feels like a really interesting beneficial feature to add to TheyVoteForYou.

It's also interesting that the grass-roots independents movements springing up for the upcoming election already look to be using TheyVoteForYou as a tool which is great - as long as they don't use it in any kind of misleading way obviously.

**Comment by mlandauer** [comment]
I'm going to spend a few days just prototyping something quick out. Initially I'm thinking we build something really really rough and ready. We don't put any effort into the user experience of the picking of the two politicians. We start with something that just shows the votes side by side for two people (just highlighting or only just showing the ones that are different?). It needs to work on mobile primarily so we're going to be incredibly restricted on the amount of information we can display. That's fine - it will really force us to think through what's important and what's not.

We might discover that showing votes is not understandable so we need to abstract this away to differences in votes on policies which makes things more complicated but will be much simpler to understand. Let's not do that initially just to keep things super simple and so we can get something decent working in a short time.

**Comment by mlandauer** [comment]
> picking up on that point about two politicians who have different views but vote the same, are you thinking of comparing two in the same party who are generally identified as being in different factions?

Yeah I guess somewhere where two politicians have **said** quite different things - which I guess means that they likely would be in different factions of the same party

**Comment by mlandauer** [comment]
After working through this it has become very clear that showing differences in individual votes is not going to be useful at all because there are just too many. So instead I have taken a different approach and focus on the differences with their agreement with policies.

**Comment by mlandauer** [comment]
Some example people to compare:
* [Zali_Steggall & Craig Kelly](https://theyvoteforyou.org.au/people/representatives/warringah/zali_steggall/compare/hughes/craig_kelly)
* [Trent Zimmerman & Craig_Kelly](https://theyvoteforyou.org.au/people/representatives/north_sydney/trent_zimmerman/compare/hughes/craig_kelly)
* [Jason Falinski & George Christensen](https://theyvoteforyou.org.au/people/representatives/mackellar/jason_falinski/compare/dawson/george_christensen)
* [Dave Sharma & George Christensen](https://theyvoteforyou.org.au/people/representatives/wentworth/dave_sharma/compare/dawson/george_christensen)
* [Rebekha Sharkie & Adam Bandt](https://theyvoteforyou.org.au/people/representatives/mayo/rebekha_sharkie/compare/melbourne/adam_bandt)
* [Rebekha Sharkie & Tanya Plibersek](https://theyvoteforyou.org.au/people/representatives/mayo/rebekha_sharkie/compare/sydney/tanya_plibersek)
* [Rebekha Sharkie & Barnaby Joyce](https://theyvoteforyou.org.au/people/representatives/mayo/rebekha_sharkie/compare/new_england/barnaby_joyce)

**Comment by mlandauer** [comment]
Some screenshots of the very early prototype (from the PR above):

![image](https://user-images.githubusercontent.com/2221/137253826-3eea8915-02f4-4256-b3f9-044d7d6e4ef0.png)
![image](https://user-images.githubusercontent.com/2221/137253898-9654eefe-770c-4f7c-adf7-5104966350d9.png)
![image](https://user-images.githubusercontent.com/2221/137253945-26bcfc56-73ee-43b4-89a9-140b89836bc0.png)

**Comment by mlandauer** [comment]
Oh yeah and you can click on the name of the policy and get the specific ways that each person voted (with links off to much more detail again):

![image](https://user-images.githubusercontent.com/2221/137254110-da50b1b9-6755-4eea-b555-2aa106076bfc.png)

**Comment by mlandauer** [comment]
Doing the simple difference in distances that this prototype is doing right now doesn't work well with our new category. Also, it makes it seem like people vote more differently than they actually do. This is because the distance measure takes into account the number of votes that people were absent on. Really when we're comparing two people we want to know about the differences on the votes they did both attend and this would then show that the difference between the votes of two people in the same party would be very very small.

So if a policy has votes, "vote A", "vote B", "vote C", "vote D" and person 1 attended "vote A", "vote B" and "vote C" and person 2 attended "vote A, "vote C" then we should consider the difference in votes just on "vote A" and "vote C" because they both attended those votes.

**Comment by mlandauer** [comment]
We're also going to need a social sharing card for this page. I'll create a separate issue for that

**Comment by katska** [comment]
Review #1251 and #1387 with and wording here together for clear and consistent language on how they voted, out of possible votes etc.
