### ISSUE TITLE
Rename "policies" to "issues" because "policies" causes some confusion

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/theyvoteforyou#1283]
Governments or organisations have policies. How we use the word is a little abstract and strange. In a sense it's good that it's a little abstract because it forces people to try to understand what it means but unfortunately that isn't always the case.

My suggestion here is that we change "policies" to "issues". That word is a little more generic and curiously enough is always the wording we use on the landing page to describe the site as a whole "How does your MP vote on the issues that matter to you?"

This suggestion was sparked by a conversation about TheyVoteForYou with several MPs' staffers where our use of the word "policy" was confused by their used of the word "policy". This confusion isn't surprising. It's important to remember that the main audience of TVFY isn't the political insider but someone who doesn't know a whole lot about the ins and outs of how politics works. However, even for this audience the word "policy" is not particularly helpful. So, why don't we avoid it all together?

To make this change we'll need to:
* Update wording in headings and help text
* Change URLs with "policies" in them to reflect the new naming convention
* Redirect the old URLs to the new ones

**Comment by mlandauer** [comment]
@mackaymackay what do you think about the idea of making this change?

**Comment by mackaymackay** [comment]
@mlandauer sounds good to me - I'm not particularly wedded to the word "policies" and can see how it could get confusing

**Comment by bobsbarrels** [comment]
`grep -rin 'polic' *` isn't pretty. But a divide and conquer approach will be good. 

Here's an overview: https://gist.github.com/bobsbarrels/e9702f916f6b78778f4e3fe434350544

Coverage and logs are excluded.

**Comment by bobsbarrels** [comment]
Note that I'm close to stalled on "Issues" refactor on a few fronts:

* "issues" as a term is not unfraught, and still potentially has multiple meaning, I've spent ages refactoring but it's still perhaps "issues" is not the best term, maybe "topics" or something else could express the meaning?

* the CRUD seems pretty tightly bound to the controller name "policies", which makes the refactor deeper than initially thought, doing it superficially is probably not an option, or at least is threading a needle

* little rails things I'm still coming up to speed with such as haven't figured out how to "soft" `301` style redirect, and updating tests is spec is less trivial than expected, etc

I'm going to commit my workings to a branch on my fork, it'd be sad to see the work go to waste, but actually can't continue without input.

Also, while this discussion is being had the term "Division" also is very detached from the conventional meaning, perhaps even further so than "Policy". Perhaps if a thorough uprooting is going to be done, it could be worthwhile doing both together?

**Comment by mlandauer** [comment]
>     * "issues" as a term is not unfraught (eg: "Issues are a group of votes which, taken together, indicate a particular stance on an issue"), and still potentially has multiple meaning, I've spent ages refactoring but it's still perhaps "issues" is not the best term, maybe "topic" or something else could express the meaning? Though I'm not an expert here :)

Yes i see what you mean. I do think that the word "issues" is a step in the right direction compared to "policies" so I do think we should go ahead even if it isn't perfect. How about:
"An issue is a group of votes which, taken together, shows a particular stance on a matter of public policy"
(This is jumping off from your suggestion in slack as well talking to @katska)

"Issues" is then what we call the bucket of votes and is the user facing concept. Then, "policy" becomes more the political wonk language so is okay to use in a more detailed explanation of what "issues" means.

I'm starting to remember how we struggled with this sentence before which is why it feels a bit awkward as it is right now.

>     * CRUD seems pretty tightly bound to the controller name "policies", which makes the refactor deeper than initially thought, doing it superficially is probably not an option, or at least is threading a needle

In the rails routing you can separate the route names from the names of the controllers. See https://guides.rubyonrails.org/routing.html

My suggestion would be be to do the minimal work to make the user-facing changes to the URLs, leaving all the controller names and variable names untouched. This way all the user-facing changes can be bundled into a single PR without it being a crazy amount of work.

Then, a bit more slowly you and I can rename controllers and do that other painful stuff. This can be done all in stages because none if it will make any difference to what users experience.

Oh and one thing which is implied here but I haven't explicitly stated is that we try not to use long-running branches, we work off of master as much as possible, master should always pass the tests and be ready for development work and we deploy very often so you can depend that master is also deployed to production.
 
>     * little rails things I'm still coming up to speed with, eg haven't figured out how to "soft" `301` style redirect, updating spec tests is less trivial than expected, etc

In the routing you can choose the type of redirect and also in the controller when you do a `redirect_to` you can choose the type of redirection.

As for updating the specs, add tests for the new redirect rules to https://github.com/openaustralia/publicwhip/blob/master/spec/routing/redirects_spec.rb and update https://github.com/openaustralia/publicwhip/blob/master/spec/requests/policies_controller_spec.rb to use the new URLs. You'll also need to update the paths of the html it's running the regression tests against. We're doing this weird thing of doing full regression tests on the output of the html because of the historical weirdness that we originally ported this application from php and we wanted to make sure we were matching everything correctly. We should definitely be working to improve the "proper" normal testing and try to remove this regression testing when we can.
 
> I'm going to commit my workings to a branch on my fork, it'd be sad to see the work go to waste, but close to not being able to continue without a thread about it.

That's great. I'm keen on working with you to get most of those turned into a PR (first for the user-facing stuff)

> Also, while this discussion is being had the term "Division" also is very detached from the conventional meaning, perhaps even further so than "Policy". Perhaps if a thorough uprooting is going to be done, it could be worthwhile doing both together?

The reason for the use of "division" is a bit more complicated. We use "division" to try to make it clear that we only consider formal votes where the house divides. Informal votes, know as "on the voices" is where most of the votes happen but there is no formal record of those which makes our job very difficult. So that's one reason. The other reason is that try (but I'm not sure we do this consistently) use the word "division" for the concept where a group of people vote and a "vote" is actually how a single person votes in a single division.
