### ISSUE TITLE
Search with mysql (rather than elasticsearch) seems to be broken in development

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/theyvoteforyou#1287]
This is only really an issue in development as we always use elasticsearch for searching in production.

There are two potential avenues:
1. We fix the mysql issue which means that it's easier to get going in development with search. However it might be confusing because it will do different things than in production!
2. Switch fully over to elasticsearch and remove the mysql search code. This has the advantage that it makes the dev environment closer to the production environment. To make it easier we would need to add some tooling to install elasticsearch locally for dev. We've done this in planningalerts and morph I think so we could copy those.

I'd be inclined to go with option 2 even though it makes more work for us.

**Comment by cofiem** [comment]
I'm not familiar with the SQL vs Elasticsearch searching, but option 2 sounds more useful if it better reflects the situation in production. Would hopefully make it easier to improve the search, as well.

**Comment by bobsbarrels** [comment]
In my recent experience I just installed both locally and it "magic worked". Elasticsearch is potentially just a necessary dependency, as @cofiem said: it reflects production, that's what you want in a development environment. 

This is a genuine concern for the reporter though, could provide support for them to install Elasticsearch.
