### ISSUE TITLE
Vagrant setup seems to be obsolete: update, replace or remove?

### ISSUE THREAD

**Issue by bobsbarrels** [openaustralia/theyvoteforyou#1288]
Having a run at getting the `openaustralia/publicwhip/blob/master/Vagrantfile` working was tough and ultimately for me a failure.

There were a range of bugs, mainly pertaining to old versions/resources no longer being available. For example the very first one upon running `vagrant up` the first time is:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'chef/ubuntu-10.04-i386' could not be found. Attempting to find and install...
..
Requested name: chef/ubuntu-10.04-i386
Actual name: bento/ubuntu-10.04-i386
```
Simply replacing to `bento` will take you so far.

There are dependency issues that I won't drill in to, but which most pertain to `puppet`. It doesn't look like I'm the first person to have trodden this path:
https://github.com/openaustralia/publicwhip/blob/master/Vagrantfile#L34

Sadly `https://apt.puppetlabs.com/puppetlabs-release-lucid.deb` referred to there at `#L34` can not be found for searching, bit-rotted. It certainly exists somewhere, if we were determined it could probably be found but then we'd need to provide it ourselves. This snarky eyebrow raising conversation kind of sets the tone: https://groups.google.com/g/puppet-users/c/81IyyMJMVaA/m/-n15m7ROo20J?pli=1 (this kind of comment would not be acceptable today thank goodness).

Hacking around that the final boss problem to which I lost was:
```
Error: Syntax error at 'Hash'; expected ')' at /tmp/modules/apt/manifests/init.pp:125 on node
```
To my understanding `puppet3` is now lost to us, and the oldest version currently available is `puppet5`, which doesn't support the same manifest syntax -- that `init.pp` being an autogenerated internal configuration manifest to which `puppet5` hard says nope. Tried a few ways to hack around this to no (easy) avail. See: https://serverfault.com/questions/882112/error-puppet-hash-expected-on-the-default-at-tmp-modules-apt-manifests-i

This is now too in the weeds and the whole manifest (https://github.com/openaustralia/publicwhip/blob/master/manifests/development_lucid.pp ) would certainly need a rework too.

But Vagrant (VMs generally) are kind of awesome for isolating environments, replicating production and getting up and running no mess no fuss (#1287 for example wouldn't exist).

Options can probably be framed:

* Lose vagrant/VMs altogether
* Try again with VMs: \
~ try to repair Vagrant; \
~ try to make new Vagrant; \
~ use other VM tech (there are options)

**Comment by bobsbarrels** [comment]
Actually doing both is probably an option with a time scale. It's not either/or: can probably deprecate Vagrant right now and add to the backlog to create new VM (that matches prod). Flavour of VM is a whole different conversation, probably to adjudicated by whoever takes on the task.

I'm working on alt installation instructions (reflecting my process) which should be made public shortly, hopefully today. Needs a bit more work and I just want to try out on a couple of previously untested environments before setting them free, probably in a `github gist`. Will link here for another different discussion as to what/how instructions could be integrated with the project here (in README or whatever).

**Comment by cofiem** [comment]
I've had a go at the Vagrant setup myself recently. I was motivated because right now the repo can't be cloned on Windows due to files with invalid (on Windows) characters (e.g. `?`).
My fork branch is here: https://github.com/cofiem/publicwhip/tree/feature-windows/local_dev
It is not complete, but might be useful for you.
