### ISSUE TITLE
Add sort by date option to policies index page

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/theyvoteforyou#1290]
We had an email this week suggesting that policies should also be sorted by date on the policy page. Currently, we only have an option to sort by name or subscriber numbers.

The user wants to be able to more easily find recent legislation when they don't know its actual name, i.e. they go to the relevant policy and look through the divisions from there, but find it a longer process due to not being able to sort policy names by date. In the case that prompted the email, they were looking for legislation related to climate change, so I imagine it took them a while to look through each climate change related policy. If the policies were sorted by date, they could go directly to the climate change policies that were most recently updated and so order their search more effectively.

_Originally posted by @mackaymackay in https://github.com/openaustralia/publicwhip/issues/1069#issuecomment-984192589_

**Comment by mlandauer** [comment]
@mackaymackay So what specifically should the date be? Should it be the date when the policy was most recently updated or somehow related to the dates of the divisions?

**Comment by mackaymackay** [comment]
@mlandauer the email referred to recent legislation, so presumably wanted the date to match the dates of the divisions. Though I'm not sure how exactly that would be done, as I imagine it would be easier to go by when the policy was most recently updated, which is usually a fairly close match to division dates (except for when I'm working through the backlog, in which case there would be a big difference between the two date options).

**Comment by Taz17** [comment]
@mackaymackay The `created_at` variable holds the date which the policy was created on the tvfy platform. I believe tvfy does not have the date which which matches the date of the divisions. 

So, I resulted to add the `Sort by Date Edited` onto the policies index page

**Comment by mlandauer** [comment]
> I believe tvfy does not have the date which which matches the date of the divisions.

We do have the dates of the divisions. It's just stored with the division object rather than the policies object

**Comment by mlandauer** [comment]
I do think the "sort by date edited" is a reasonable approach
