### ISSUE TITLE
Adapt and share "strong" vote definition where it's most useful

### ISSUE THREAD

**Issue by katska** [openaustralia/theyvoteforyou#1323]
Where should the definition of a strong vote, described in #1314 go, to be useful to people visiting theyvoteforyou.org.au?

In TheyVoteForYou definitions sometimes appear in context with a link to an explanation[ for example ](https://theyvoteforyou.org.au/people/representatives/hindmarsh/mark_butler)
"94% attendance. Explain attendance"

<img width="918" alt="tvfy_screenshot_explain" src="https://user-images.githubusercontent.com/1001129/151902830-279f7bb6-d7a8-481b-84f1-0b6488bc9147.png">

Consistent with this approach, one place where contextual help might be useful is in [a division where a strong vote appears](https://theyvoteforyou.org.au/policies/86#divisions)

<img width="1158" alt="tvfy_screenshot_strong" src="https://user-images.githubusercontent.com/1001129/151902920-b3b6cbd0-c3df-4b69-b786-e3aee661d1ff.png">

Would it make sense that "Explain Strong Vote" appear here? That seems clunky. 

* What a strong vote is can be added to at https://theyvoteforyou.org.au/help/faq 

Where else should this information show up?

**Comment by katska** [comment]
if we are still having 'strong' votes or an equivalent explanation

**Comment by mlandauer** [comment]
I think the change suggested in #1271 provides a really clear place to explain what a "strong" vote is because it will have it's own little section.
