### ISSUE TITLE
Provide helpful guidance for people sharing content on social media or putting up posters using TVFY around electoral advertising legislation

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/theyvoteforyou#1335]
In that case we're not the ones doing the electoral advertising but other people are and we want to help them to ensure that they understand their obligations under the law. This information is particularly important in places on the site where we allow social sharing.

**Comment by cofiem** [comment]
Here's an initial go at a [help / faq](https://theyvoteforyou.org.au/help/faq) entry around electoral communications and authorisation requirements:

Title:
What should I know when sharing information from  _They Vote For You_ ?

Content:
The Australian Electoral Commission (AEC) is responsible for running Federal elections in Australia.
One part of their job is to make sure that people who vote know *who* is sharing information that is trying to influence the *way* people vote.
The people and groups who need to say who is providing the information include political parties, groups supporting political parties, members of parliament, and candidates.
It can be tricky to work out if you need to say who is sharing the electoral information (the "Authorisation").

We cannot tell you if you do or don't need to add authorisation details.

Have a look at the AEC's Questions and Answers page. We suggest the [authorisation particulars table](https://www.aec.gov.au/About_AEC/Publications/Backgrounders/authorisation.htm#particulars), the [non-printed and social media communications](https://www.aec.gov.au/About_AEC/Publications/Backgrounders/authorisation.htm#otherComms) questions, and the information about when [authorisation is not required](https://www.aec.gov.au/About_AEC/Publications/Backgrounders/authorisation.htm#authNo).

**Comment by mlandauer** [comment]
Thanks so much @cofiem for jumping into this. I like the straightforward style of what you've written. It feels very much in keeping with the writing elsewhere on the site. I also really like  that you say "it can be tricky to work out.."

I wonder, would it be possible to provide some broad advice based on the AEC advice links and the act that the AEC is working under while at the same time linking to the stuff that you have there for more details or more specific information?

I feel like on righttoknow.org.au in the help section we worked really hard to take some really complicated legal stuff and distill down to something much more straightforward. We don't want to say anything that's outright wrong but we somehow want to be useful and helpful rather than just say "look at the AEC" (that's not what you're doing here, but I'm just using that as an example)

@katska would you be able to take a look at this as well?
