### ISSUE TITLE
Social Card 2: Sharing an MP's page

### ISSUE THREAD

**Issue by tseyiokorodudu** [openaustralia/theyvoteforyou#1349]
### Social Card 2 is for when someone shares a member's page (https://theyvoteforyou.org.au/people/senate/tasmania/eric_abetz)

Currently when a person shares an MP's page this is what it looks like...

**Image 1**
<img width="554" alt="image" src="https://user-images.githubusercontent.com/31440427/155038416-7553dd2c-82a8-454f-995c-c18878f6fa4a.png">

### Design Direction

Right now, the thinking is to use the same design layout as social media card 1 because they are both member focused and have the same layout on TVFY websites. 

#### Option 1: Follow the design of social card one exactly

![Twitter header - 20-2](https://user-images.githubusercontent.com/31440427/155038826-e63081a5-d7fc-4223-aeb4-de1348825a72.png)

The name and position were emboldened because I think in this context they are quite important and it feels like they get lost in the other text if written plainly. 

#### Option 2: Follow the design layout of the web page, where the name is separate from the position.

![Twitter header - 15-2](https://user-images.githubusercontent.com/31440427/155039173-03c2ebda-c3c0-43d6-840c-53031b2ceeae.png)

### The questions 
- How similar do we want the design of the cards to be? Does it even matter?

- Which of the options do we prefer?

- Copy?... In the cards above we have "Want to know how the Liberal Party Senator for Tasmania votes on issues that matter to you?". Another option is "Find out how the Liberal Party Senator for Tasmania votes on issues that matter to you." 

**Image 2**
<img width="728" alt="image" src="https://user-images.githubusercontent.com/31440427/155040133-a2b39f6f-5a73-48ed-bbf9-a664b8afb7e1.png">

- Right now, we have opted to not include their attendance or rebellion status because looking through the sharing history on twitter, I noticed that very few people actually took a screenshot of the MP's page which would show the attendance or rebellion status (image 2 above) as most people just shared the page (image 1).... but I'm also wondering if the rebellion and attendance info is too important to omit?

**Comment by mlandauer** [comment]
>     * How similar do we want the design of the cards to be? Does it even matter?

I don't think it's inherently important for the two cards to have a similar design. I think like everything else if there's good reasons for things to be different then they should be different! They shouldn't be different just for the sake of it.

>     * Which of the options do we prefer?

It's definitely not about what I prefer! It's about working towards a design solution together :-) I think option 2 is clearer from the standpoint of making the name of the politician more readable and that is obviously one of the most important pieces of information on this card (next to their image of course).
 
>     * Copy?... In the cards above we have "Want to know how the Liberal Party Senator for Tasmania votes on issues that matter to you?". Another option is "Find out how the Liberal Party Senator for Tasmania votes on issues that matter to you."

The wording does feel quite long-winded at the moment.

One big way this card is currently very different in nature to card 1 is that it doesn't actually have any useful information on it. It's only really useful as a way to get people to look at the site. Is the idea to make a separate card (sorry if you've already said this elsewhere!) for "Policies that Eric Abetz voted strong for" as an example that would directly have useful information on it.

If this is a card with little directly useful information the link to the site needs to be much more prominent, don't you think?

**Comment by mlandauer** [comment]
I don't think rebellions and attendance are important enough to put on the card.

**Comment by katska** [comment]
So the aim is to have a snappy call to action?  
Find out how "NAME" stands on issues that matter to you!

**Comment by katska** [comment]
That's a bit shorter. @tseyiokorodudu and I just discussed the circumstances where people share this card. I seem to remember in the past when there's a change of machinery of government or get a different position (for example enter Cabinet or are rumored to be in line for a top job) then there's a higher level of scrutiny on their voting record. This is where a general card is useful as well as the case Tseyi shared to begin with.

**Comment by tseyiokorodudu** [comment]
>Is the idea to make a separate card (sorry if you've already said this elsewhere!) for "Policies that Eric Abetz voted strong for" as an example that would directly have useful information on it?

Yes that is the idea. We figured it is better to do general cards like this first before the "specific information card (i.e. Eric Abetz voted strongly for ... etc)".

> If this is a card with little directly useful information the link to the site needs to be much more prominent, don't you think?

From a logical perspective, I think this makes sense. So it is definitely something I will consider as I work.

> Find out how "NAME" stands on issues that matter to you!

This makes me assume that the MP's position isn't important enough like rebellions and attendance. Is this assumption right?

**Comment by tseyiokorodudu** [comment]
Sticking with the same design as social card 1 for now.

I changed the text to what @katska suggested. @mlandauer does it still feel long-winded?

Also increased the size of the url link a bit. 

![Twitter header - 22-3](https://user-images.githubusercontent.com/31440427/155252727-4c3ceb0d-37c6-40b3-b869-19be50d96427.png)

I know the name of the politician is not highlighted in this but I feel there is a simplicity and succinctness to this that makes it work. 

Thoughts?

**Comment by mlandauer** [comment]
Yup, I agree. It's succinct and clear and doesn't need any more embellishment. One small suggestion: How about "votes" instead of "stands" so it would be "Find out how Eric Abetz votes on issues that matter to you!". Then the wording would line up with the wording on the landing page.

**Comment by katska** [comment]
of course yes, it's all about the votes!!

**Comment by tseyiokorodudu** [comment]
Here is the implemented version of the card.

![image](https://user-images.githubusercontent.com/31440427/155461102-7a208204-572e-403e-9ba9-35de83236f59.png)

Thoughts please?

**Comment by katska** [comment]
Oooh! @tseyiokorodudu looks good to me!  Is there something you think needs to tweak at this point?

**Comment by mlandauer** [comment]
Looks good to me @tseyiokorodudu. One tiny tiny suggestion. Can you remove the exclamation mark? I'm finding it little too "excited puppy" for me. And I'm also assuming the higher resolution image can go in there too now.

**Comment by mlandauer** [comment]
The view part was added in #1367 and that's merged and rolled out to production.

@tseyiokorodudu @Taz17 could you please put together a PR to render the images in the screenshotting rake task.
