### ISSUE TITLE
review supporting organisations - add / remove / check in?

### ISSUE THREAD

**Issue by katska** [openaustralia/theyvoteforyou#1358]
Noticing #1346 prompted me to check in on the supporting organisations page. 

Maybe testimonials are important, institutional support from other trusted organisations I think is also an important part of the picture, if not eye catching in the moment.

@mlandauer how would you feel about me approaching the Accountability Roundtable to become a supporting org? It seems like a good fit, and it's a straightforward ask.

**Comment by mlandauer** [comment]
> @mlandauer how would you feel about me approaching the Accountability Roundtable to become a supporting org? It seems like a good fit, and it's a straightforward ask.

Sounds like a good thing to me if it's a quick win!

**Comment by katska** [comment]
[ ] find previous supporting organisations call out
[ ] send ! 
[ ] report back here

**Comment by katska** [comment]
(contacted to see if they'd welcome an offer become a supporting org)

**Comment by mlandauer** [comment]
@katska this is at the top of the todo list for TVFY right now. Any progress on this or should I mark this as done?

**Comment by katska** [comment]
I really only had one org in mind to begin and I haven't heard back from them. So it's definitely not top of the list. Can we review in 2 weeks rather than mark done? I'll chase up and see if they're coming aboard.

**Comment by mlandauer** [comment]
I removed a couple of supporting orgs in 77a6af9fcb7d01879eee86ee430616aa847140d9 - one was dead (sunlight). The other has changed name a long time ago and maybe mission?

**Comment by mlandauer** [comment]
@katska could you have another look at this soon?

**Comment by katska** [comment]
@mlandauer was sad to see undación Ciudadano Inteligente down too :(

**Comment by mlandauer** [comment]
I'm going to close this as done now
