### ISSUE TITLE
Add explanation about COVID attendance issues to TVFY

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1383]
MP Wilkie's team has written and raised concerns about the fact that we don't currently explain anything about the COVID attendance arrangements on our site, i.e. that reps were often attending remotely but could not vote.

This explanation could be put in the [FAQ section on attendance](https://theyvoteforyou.org.au/help/faq#attendance), as this is where the link "Explain Attendance" on all reps' voting records leads.

I plan to draft something for this purpose, but don't have time this week. I've put it on my to-do list and created this issue so I don't forget.

**Comment by cofiem** [comment]
I'm not sure if it's useful, but it looks like the *daily* attendance record now includes whether anyone attended via video.

For example [HVP No 167 - 17 February 2022](https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;adv=yes;orderBy=customrank;page=0;query=attendance%20Dataset%3Avotes,voteshistorical,journals,journalshistorical;rec=0;resCount=Default)

As [discussed in the past](https://github.com/openaustralia/openaustralia/issues/651), it's not clear how or if the division attendance can be combined with the daily attendance.

**Comment by mlandauer** [comment]
@mackaymackay if I recall correctly during our first zoom meeting with Wilkie's team we asked for further information about the COVID attendance arrangements especially anything written down officially that we could refer to. I'm pretty sure we didn't receive anything. There must be something written down solidly somewhere, right? But I can't seem to find anything... Did you already find something?

**Comment by mlandauer** [comment]
One other thing we could do to make this more prominent where it's relevant is we could add a warning box (a milder version of what we did for draft policies)
![image](https://user-images.githubusercontent.com/2221/161467378-ef78e41f-fbc8-4d1e-ae41-d80d690b7959.png)
which explains that this division (or related policy) took place while COVID-19 restrictions were in place. Some members would not have been able to attend and so this could skew their record.

**Comment by mackaymackay** [comment]
@mlandauer  I'm not aware of receiving any further information from Wilkie's team.. I've found a report about COVID related changes in the House: https://www.aph.gov.au/Parliamentary_Business/Committees/House/Procedure/ResponsetoCOVID-19/Report   It contains some useful info that could be a good starting point for when I get to drafting something for this.

_Re the warning box:_

Having a warning box isn't a bad idea, but I feel like it would be more useful for a warning box to be about the incomplete nature of the record (e.g. **Note!** These policies are made up of **divisions** (formal votes) rather than the far more common 'on the voices' votes, so **only tell part of the story**) rather than one on COVID attendance issues. 

While COVID attendance was a big issue from a democratic perspective, I'm not sure how much it significantly changes how users should read our policy pages. As in, how does putting them on notice about COVID attendance issues change how they should interpret the voting pattern on a given policy? Doesn't it just mean there were fewer votes being counted, in which case the voting records are sparser? Yes, this may skew individual records and perhaps even the broader policy breakdown, but I'm not convinced it does so enough to warrant a warning box.

On the other hand, our incomplete record due to our reliance on divisions is a huge issue and most definitely skews the records. So if a warning box is an option, that's the issue that should be highlighted, I think.
