### ISSUE TITLE
Create a 'How to check accuracy of TVFY guide'

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1386]
Put in one place (perhaps a blog?) a simple guide on how to check that the info on TVFY accurately reflects the official record.

This is prompted by an email asking about the accuracy of a particular voting record, and has been asked in the past by other sources.

I've assigned this to myself and created this issue as a reminder.

**Comment by mlandauer** [comment]
A slight aside: I really like using the blog as a kind of writing "prototyping" place. It's a great way to be able to write something time-sensitive without having to figure out where it fits in with other things 

However, if we keep finding ourselves referring to old blog post for TVFY that's probably a signal that we should figure out how to include the writing into the site proper. It's more work but there users are more likely to find it themselves and we can also more actively guide them to the relevant content

**Comment by mackaymackay** [comment]
@mlandauer agreed. Perhaps it's time to redo the TVFY FAQ page and add answers questions like this one, and others that commonly prompt me to link old blogs.

**Comment by katska** [comment]
@mackaymackay thank you for getting this going :)

**Comment by katska** [comment]
The words are [here ](https://docs.google.com/document/d/16G4ObYVgTXmdqyU8qHUxslSWaozU9KMNS3HdWS0tGbY/edit)
Add straight to the [Help page?](https://theyvoteforyou.org.au/help/faq)

**Comment by mlandauer** [comment]
This was fixed by #1427 and #1428
