### ISSUE TITLE
On person policy page explain that the divisions shown are just those that the person could have attended

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/theyvoteforyou#1387]
This is not explicitly said anywhere and so could lead to confusion. For example, on https://theyvoteforyou.org.au/people/representatives/clark/andrew_wilkie/policies/46 Andrew Wilkie is shown as "We can't say anything concrete about how Andrew Wilkie voted on increasing access under Freedom of Information law" and it lists one division as being connected to the policy.

What isn't obvious is that if you go to https://theyvoteforyou.org.au/policies/46 you can see that there are in fact **7 relevant divisions**. On the person-policy page it only shows one because Andrew Wilkie could only have voted on one of those policies just based on when he's been in parliament and in which house.

So I was thinking we could say something like:
"Andrew Wilkie was able to vote on 1 out of 7 divisions related to the policy. This is based on being in the correct house (House of representatives / Senate) and being a member of parliament when the division took place"

I don't think this wording is very good but I just wanted to get a first version written down so other people could comment on it ;-)

@katska @mackaymackay thoughts? feedback?

**Comment by katska** [comment]
@mlandauer yes. Good idea! How bout something like 

Andrew Wilkie has voted **once** on this issue, out of only one possible division in **the House of Reps**.
All together there have been **X** divisions in the **House of Reps** and **Y** divisions in the Senate, between **date 1** and **date 2**.

and this might be another opportune moment to include
However there may have been other votes agreed on the voices, which are not formally recorded against his name. 
Could "Contact them to find out more?" be an option here?

@mackaymackay @mlandauer How does that read/scan? Also, we could reveal/link to/ include other words depending on how much explanation and how much to drill down into the context, such as 

X votes out of a possible Y in the House of Reps 
Was not an MP when ZZ votes between Date A and Date B took place.
Has never been eligible to vote in the Senate
or X votes out of a possible Y in the Senate (for people who have been in both houses)

Well before I go thinking about it too much there's my initial suggestions.

**Comment by mackaymackay** [comment]
@katska @mlandauer  This is a great idea. The wording is difficult though... I've tried combining what you both had into:

> [Andrew Wilkie] has voted [once] on this issue. Altogether, there [is one division] / [are >two divisions] currently attached to this policy that [he] could have voted in, which means [he] has been absent for [no] relevant division[s].

The bits in square brackets are the bits that would change according to the circumstance. The issue with this wording is it would need a singular ("is") and plural ("are") option in the second sentence - I'm not sure how doable that is?

I also like the idea of having something like Kat suggested, i.e. "However there may have been other votes agreed 'on the voices,' which are not formally recorded against his name." And having a "Contact them to find out more" option, which could link to the aph.gov.au [contact page](https://www.aph.gov.au/Senators_and_Members/Guidelines_for_Contacting_Senators_and_Members).
