### ISSUE TITLE
Social Card 5: Sharing a categories of votes under a policy. eg. Voted generally against.

### ISSUE THREAD

**Issue by Taz17** [openaustralia/theyvoteforyou#1390]
Social card 5 is for when a user shares how members voted for a certain policy (including what cannot be decided on)

The categories can be found on a members page. e.g. https://theyvoteforyou.org.au/policies/86

The card will show each individual section labelled 1, 2, 3, 4, 5 in this image (there will also be cards for the sections that cannot be seen in this screenshot
![image](https://user-images.githubusercontent.com/86769131/161666971-40d6a001-3762-442f-a194-4080b34bfdbb.png)

Here is the first version of the card.
![image](https://user-images.githubusercontent.com/86769131/161667190-1d9a9a0a-2b17-4663-a9f6-603d8ce64d1b.png)

To me the card title looks off because of the thin font.

**Comment by tseyiokorodudu** [comment]
> To me the card title looks off because of the thin font.

That was a mistake on my part. But it is an easy fix.

**Comment by mlandauer** [comment]
There's an anchor on each of the sections so you can link directly to them. For example https://theyvoteforyou.org.au/policies/1#not_enough

It would also make sense to name each card by the anchor name (which is supposed to be fixed, even if the human readable name of the section gets updated)

**Comment by Taz17** [comment]
Here is an update on the card!

We made the card title a bit bolder and added the anchor at the end of the URL. 

![image](https://user-images.githubusercontent.com/86769131/161874266-e721c92b-6323-454e-a392-027b0ca3119a.png)
