### ISSUE TITLE
possible friends not shown for Craig Kelly

### ISSUE THREAD

**Issue by katska** [openaustralia/theyvoteforyou#1403]
Craig Kelly does not show as having any possible friends.

https://theyvoteforyou.org.au/people/representatives/hughes/craig_kelly

<img width="1022" alt="Screen Shot 2022-04-07 at 1 11 55 pm" src="https://user-images.githubusercontent.com/1001129/162112812-cd0db50e-5d93-4bea-a083-2f213b0bf785.png">

**Comment by mlandauer** [comment]
Seems to have been a temporary blip. It all looks fine to me now. So, closing.
