### ISSUE TITLE
track notable uses & mentions

### ISSUE THREAD

**Issue by katska** [openaustralia/theyvoteforyou#1405]
Noteable uses being those that come to our attention where TVFY functionality of people sharing voting position on issues.
[Honest Government ads ](https://www.thejuicemedia.com/honest-government-ad-united-australia-party/)

Noteable complaints where politicians are complaining about They Vote For You
https://www.theguardian.com/australia-news/2022/mar/25/liberal-andrew-bragg-accused-of-showing-disdain-for-free-speech-with-legal-threat-to-they-vote-for-you-site
https://www.smh.com.au/politics/federal/pack-of-lies-liberals-take-legal-action-over-they-vote-for-you-site-20220322-p5a6wm.html 

Noteable mentions those more focused on They Vote For You  
where "One website is forcing MPs to put their money where their mouths are by sharing how they vote on the issues." https://news.com.au/national/this-website-will-tell-you-what-your-mp-voted-for/news-story
OR
"one website is holding your local Members of Parliament accountable and taking an ‘actions speak louder than words’ approach, by showing how they voted on the issues"
https://www.news.com.au/national/this-website-will-tell-you-what-your-mp-voted-for/news-story/9e48918aa62ac5c4f196b5e53e4339ec
Kassia Byrnes, Youth Editor News.com.au

Uncategorised starting point to look for uses
https://www.tiktok.com/search?q=theyvoteforyou&t=1649303304103
https://twitter.com/search?q=%23theyvoteforyou&src=typed_query&f=live

"Shutting Down They Vote For You" Nov 21
https://www.youtube.com/watch?v=ygeZdbgOuV8

**Comment by mlandauer** [comment]
@katska what do you mean exactly by "track"?

**Comment by katska** [comment]
> @katska what do you mean exactly by "track"?

make a note of.

**Comment by katska** [comment]
@mlandauer is there somewhere else you want to keep a record?

**Comment by mlandauer** [comment]
@katska it's not clear to me what you're concretely suggesting and what would possibly be considered "done" for this issue. Right now it just sounds like a vague statement of a desire to write down some information.

I'm going to close this. Please reopen if you can suggest a way to explain this as a feature in the application and something that can be finished.
