### ISSUE TITLE
Social sharing card for comparing two people page

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/theyvoteforyou#1414]
Here's an example page of the work in progress for comparing two people:
![image](https://user-images.githubusercontent.com/2221/166355189-2b01aff7-a44c-4f6f-b03f-e4e4c83e7dac.png)

We need a design for the social card. @katska could you do a first pass of this please?

Then, we'll need to make an html version of the page similar to the other ones. Then, we need to add to the rake task for generating the screenshots. Then we add the screenshots to the social sharing code in the html of the original page.

**Comment by katska** [comment]
@Matthew - based on this one 
<img width="603" alt="Screen Shot 2022-05-03 at 10 54 00 am" src="https://user-images.githubusercontent.com/1001129/166400786-98a5e70e-9791-43f4-9874-fe187008c6ca.png">
<img width="525" alt="Screen Shot 2022-05-03 at 1 04 14 pm" src="https://user-images.githubusercontent.com/1001129/166400789-2ec8a2f6-ac44-4c97-b11c-46744b526889.png">
<img width="528" alt="Screen Shot 2022-05-03 at 1 17 22 pm" src="https://user-images.githubusercontent.com/1001129/166400792-5058330d-c2cc-43e7-a266-be8db23e1283.png">

its a Canva file that I've shared with you also

**Comment by katska** [comment]
Here's a rough version at 1200 x 628
![simple](https://user-images.githubusercontent.com/1001129/166610814-f0afa206-2bd2-406e-b1b9-9bb54394c3c7.png)

[Canva file](https://www.canva.com/design/DAE_sGsYvFE/W9USjjw2eC-Gb7aSKrPp0g/view?utm_content=DAE_sGsYvFE&utm_campaign=share_your_design&utm_medium=link&utm_source=shareyourdesignpanel)

**Comment by katska** [comment]
@mlandauer assign back to me when/if you need anything else

**Comment by mlandauer** [comment]
First pass at implementation:

![image](https://user-images.githubusercontent.com/2221/166856567-1429f52f-a86d-42a4-909f-13797949c933.png)

**Comment by katska** [comment]
@mlandauer looking good!

**Comment by mlandauer** [comment]
Just realised a big problem. There are over 200,000 cards like this one for our current database of people. That's way too many I think to create overnight. It makes me wonder if we just need to make a more generic card for the time being until we can figure out a way to maybe generate the cards on-the-fly and cache the results. This would mean that we would only generate cards for those that are used which would be a good thing and save a lot of energy.

**Comment by mlandauer** [comment]
Actually let's just drop a social share card for this page. It's looking like a bit of a blocker otherwise. It will make social sharing of this page less engaging but it's frankly more important that we get something up and running soon
