### ISSUE TITLE
for the 2 people policy comparison page, shorten opening explanation

### ISSUE THREAD

**Issue by katska** [openaustralia/theyvoteforyou#1419]
On a comparison page, such as [Adam Bandt vs Susan Lamb](https://theyvoteforyou.org.au/people/representatives/melbourne/adam_bandt/compare/representatives/longman/susan_lamb)
Simplify the first sentence in 
**How do their votes on policies compare?**

from 
Policies are groups of votes related to an issue. Here we only show policies related to divisions in which both people voted and neither are characterised as “We can't say anything concrete about how they voted on”.

to 
**"Policies are groups of votes related to an issue. We only show policies where we have enough voting information on both people. "**

and move this section to a help area or have it reveal/drop down so that the reader can get to the main information sooner.

"Now this is where it gets a bit tricky… Two people might vote the same way on votes they both attended, so their votes are 100% in agreement. They might also have voted in a way we’d describe differently when looking at all of one person's votes. If the other person didn’t or couldn’t have attended those votes we leave those out of the comparison. Because that just wouldn’t be fair now, would it?
"

which looks like this:
<img width="845" alt="Screen Shot 2022-05-09 at 1 50 12 pm" src="https://user-images.githubusercontent.com/1001129/167344196-9890ff37-c5a5-4e78-b8c0-7efbad406934.png">

**Comment by mlandauer** [comment]
Decided to move the paragraph with the detailed explanation to the detail page of person/person/policy because that's where it's most relevant.
