### ISSUE TITLE
Voting data incorrect (12th May 2021, 4:25 PM, Senate)

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1437]
In the Senate division [12th May 2021, 4:25 PM](https://theyvoteforyou.org.au/divisions/senate/2021-05-12/9), the voting data is incorrect. For example, we have the Greens and One Nation voting 'Yes' together, when they actually voted against each other on this, with the Greens voting 'No' (see the [Senate Journals](https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;db=CHAMBER;id=chamber%2Fjournals%2F73d52b28-3358-4802-b96e-097589997297%2F0025;query=Id%3A%22chamber%2Fjournals%2F73d52b28-3358-4802-b96e-097589997297%2F0000%22))

**Comment by mlandauer** [comment]
Thanks @mackaymackay for reopening this

**Comment by mackaymackay** [comment]
I gave a link to the Senate Journal above, but I'm only getting bad gateways when I try to access it today... but the Hansard still seems to be functioning, so you can find the correct voting data on their [12 May 2021 record](https://www.aph.gov.au/Parliamentary_Business/Hansard/Hansard_Display?bid=chamber/hansards/5d7154b6-80d6-4733-ad27-6f37db4fb595/&sid=0000)

**Comment by ianheggie-oaf** [comment]
@benrfairless - We may need a "data cleanup" effort and address these issues - what do you think?
