### ISSUE TITLE
Free vote on Restoring Territory Rights Bill 2022

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1441]
The [third reading vote](https://theyvoteforyou.org.au/divisions/representatives/2022-08-03/3) for the Restoring Territory Rights Bill 2022 was a conscience vote, but is currently coming up as having 24 rebellions.

**Comment by mackaymackay** [comment]
The [second reading vote](https://theyvoteforyou.org.au/divisions/senate/2022-11-24/1) in the Senate was also a free vote. The third reading vote will be also.

**Comment by mlandauer** [comment]
Looks like there are four divisions in all related to the same bill all of which are currently showing a lot of "rebellions".

In representatives:
* https://theyvoteforyou.org.au/divisions/representatives/2022-08-03/3

In the senate:
* https://theyvoteforyou.org.au/divisions/senate/2022-11-24/1
* https://theyvoteforyou.org.au/divisions/senate/2022-12-01/11
* https://theyvoteforyou.org.au/divisions/senate/2022-12-01/12

**Comment by mlandauer** [comment]
The caches and everything should get updated in production automatically sometime this morning. Until then it will still show votes on this bill as sometimes being rebellions.
