### ISSUE TITLE
Vote agreement needs to consider absolute, not just relative, vote comparisons

### ISSUE THREAD

**Issue by wisdomtooth** [openaustralia/theyvoteforyou#1444]
Vote agreement is currently ranked by the percentage of equal votes in which two politicians voted. That is ranking agreement between politicians that have voted the same on the 5 bills they both voted on higher than between politicians that have voted the same 49 out of 50 votes they both participated in. A column with the total number of agreed votes should be included so that site users can see what the percentage is of. A further enhancement could involve an agreement score based on both the percentage and number of agreed votes. If you, for instance, use cosine similarity coefficient—simply subtracting opposite votes from agreed votes, and dividing by the geometric mean of total votes from each politician—you'll not only have a score that is discounted for low coattendence, but also produces negative scores when politicians disagree on most votes.

**Comment by wisdomtooth** [comment]
> this is still a worthy issue

Thanks for reopening it, @katska. I've just revisited this ticket, and can barely understand what I wrote 😅

I remember what the issue is, but perhaps you could add to it formulating it from your own pov.

Thanks again.

**Comment by katska** [comment]
@wisdomtooth I'm not actively looking at this until such time as there's potential to review and add nuance to how these relationships are represented. If *you* have thoughts in the meantime, or next time the bot reminds us to keep this open please chime in!
