### ISSUE TITLE
Adding conflict of interest declarations to TVFY

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1445]
We've received an email suggesting that we add a section on conflict of interest declarations. This would be a big change, and is likely beyond our capacity at present, but it would add to TVFY's mission in terms of increasing transparency and holding representatives to account.

Description from the email:

> In this area, each MP would have listed any stocks, investment properties, shares, family trusts, etc that they own in an easily viewable and accessible way. I would also love to see this consolidated to a single page (with table) where one can view all MPs with associated party too, maybe even sort by numbers of conflict (who has the most investment properties?) This information is already accessible [here](https://www.aph.gov.au/Senators_and_Members/Members/Register) but requires downloading a PDF for each MP, which seems to be a combination of electronically generated PDFs and scanned sheets of paper. I understand it would be an enormous effort to go through each MP by hand to consolidate all the information into a database, but doing it once would mean there is a lower bar of entry for that information to the public.

**Comment by cofiem** [comment]
It looks like OpenPolitics have extracted some of that information: https://openpolitics.au/search
