### ISSUE TITLE
Update new MP and senator photos

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1447]
We currently have several MPs and senators without an image on TVFY, which is causing some [problems on the policy pages](https://github.com/openaustralia/theyvoteforyou/issues/1443).

As of today (25/11/22) on the official parliament site aph.gov.au, only one senator is still lacking an image. Four MPs are still missing images.

**Comment by mlandauer** [comment]
Now have updated them on openaustralia.org.au

**Comment by mlandauer** [comment]
I've flowed the changes through to theyvoteforyou.org.au. Looks like we have a photo for every current MP and senator and with the changes I made a bit earlier at least if a new person comes along and we don't have a photo the policy pages will still work.
