### ISSUE TITLE
Can’t access any persons page

### ISSUE THREAD

**Issue by ArabellaTheDuckling** [openaustralia/theyvoteforyou#1459]
It just says:

“We're sorry, but something went wrong
Try again and contact us if you're still having problems.”

**Comment by katska** [comment]
There's a short window when this happens, and the problem related to https://github.com/openaustralia/theyvoteforyou/issues/1269

@ArabellaTheDuckling My understanding is that it's daily and scheduled when the site is least busy to minimise impact to people coming to the site. Can you say more about the problem if it's persisting for you?
