### ISSUE TITLE
Divisions not appearing on TVFY

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1464]
We're missing divisions on TVFY since 11 May (as far as I can tell).

The Hansard on [openaustralia.org.au](http://openaustralia.org.au/) is also missing but in an oddly specific way: we don't have 11 May or from 24 May onwards but we do have 22-23 and 30 May, which were all days on which there were no divisions.

Put visually in terms of the House of Reps, the blue circles were uploaded onto [openaustralia.org.au](http://openaustralia.org.au/) fine, but there were no divisions in the House those days. The red circles were not uploaded and there were divisions on those days.

![image](https://github.com/openaustralia/theyvoteforyou/assets/6345406/ac1118d2-ac5d-48c6-9035-ebdbb6f11f8f)

The only thing I can see that we're not up to date on is the independent status of MP Andrew Gee (https://github.com/openaustralia/openaustralia-parser/pull/154) and Senator Lidia Thorpe (https://github.com/openaustralia/openaustralia-parser/pull/155) and Dutton's new ministry (https://github.com/openaustralia/openaustralia-parser/pull/157), but I don't see why those things would suddenly be causing this issue..

**Comment by mackaymackay** [comment]
Just as an update, this issue is continuing in June, that is, divisions are still not appearing on TVFY and those days are also not appearing on https://www.openaustralia.org.au/hansard/

**Comment by mackaymackay** [comment]
Note that none of the previous sitting fortnight (13-22 June) has appeared on either TVFY or openaustralia.org.au

**Comment by mlandauer** [comment]
Looks like the failure on May 11 is down to Mary Doyle https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=299962 who was elected in a by-election not being added. I'm not sure if there is an outstanding PR for that. Either way, I'm going to try to work through this stuff today to try fix it up.

**Comment by mlandauer** [comment]
I added Mary Doyle and merged the outstanding pull requests for adding / updating people. I reran all the parsing of the speeches from May 11 until today and there were no further errors. So, fingers crossed, that's addresses the issues. I've brought the latest data into theyvoteforyou as well and ran all the jobs for updating the caches (well, that last bit is still running...). Oh yes one more thing also re-ran the rake task to import the latest member images.
