### ISSUE TITLE
Divisions/Hansard not uploading to TVFY/OA + Fadden by-election

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1468]
### The issue: 

Since 31 July (and with the exception of 1, 2 & 8 August), the Hansard transcript hasn't been uploading to OpenAustralia.org.au and nor have the relevant divisions appeared on TVFY. 

### Likely culprit: 

Looks like there was a Fadden by-election on 15 July. I've attempted updating the relevant files, but can't work out how to create a pull request with the new interface (I'm sure I've done this before, but it's beyond me this morning). So I've typed the edits up here as a sort of pseudo do-it-yourself pull request:

*To be added to [people.csv](https://github.com/openaustralia/openaustralia-parser/blob/master/data/people.csv)*
1016,306489,Cameron Caldwell,,

*Edit to [representatives.csv](https://github.com/openaustralia/openaustralia-parser/blob/master/data/representatives.csv)*
From: 443,,Stuart Rowland Robert,Fadden,Qld,24.11.2007,,,still_in_office,LIB
edited to: 443,,Stuart Rowland Robert,Fadden,Qld,24.11.2007,,18.5.2023,resigned,LIB

*To be added to [representatives.csv](https://github.com/openaustralia/openaustralia-parser/blob/master/data/representatives.csv)*
818,,Cameron Caldwell,Fadden,Qld,15.7.2023,,,still_in_office,LNP

**Comment by mackaymackay** [comment]
I managed to create pull requests: https://github.com/openaustralia/openaustralia-parser/pull/159 and https://github.com/openaustralia/openaustralia-parser/pull/160

Turns out that I just needed to press 'commit changes' and _then_ an option would pop up to create a pull request. I thought if I pressed 'commit' it would go straight to the master, so had avoided trying that until now.

**Comment by mlandauer** [comment]
I've merged the two pull requests, updated the parent module, pushed to production and am currently running the following on the server:
```
./parse-speeches.rb 2023.7.31 2023.11.29
```

**Comment by mlandauer** [comment]
Running the following on theyvoteforyou:
```
bundle exec rake application:load:members RAILS_ENV=production
bundle exec rake application:load:divisions[2023-7-31,2023-11-29] RAILS_ENV=production
```

**Comment by mlandauer** [comment]
@mackaymackay hopefully that brings things up to date. Please let me know if there are any other issues.
