### ISSUE TITLE
API question and examples

### ISSUE THREAD

**Issue by mediocreatmybest** [openaustralia/theyvoteforyou#1469]
Hi, 

I’ve been trying to find out information on the api usage to search for a person by name.
Is this possible at all?
You can search based on ID, but how do you get a list of previous members and their ID to use this function?

thanks!

**Comment by mackaymackay** [comment]
Hi @mediocreatmybest, I'm not sure I understand your question, but we have a list of all the senators and MPs on They Vote For You at [people.csv](https://github.com/openaustralia/openaustralia-parser/blob/master/data/people.csv). The APH ID mentioned on that page comes from the end of their APH homepage address, e.g., for Anthony Albanese, his page is at https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=R36 and his APH ID is R36.
