### ISSUE TITLE
December divisions not on TVFY

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1474]
No December divisions have been uploaded on TVFY, for either the House of Representatives or the Senate.

After a search, I've discovered that Senator Marise Payne has left the Senate and been replaced by former MP Dave Sharma as of 30 Nov - so this might be the root cause of the issue?

I've created a [pull request](https://github.com/openaustralia/openaustralia-parser/pull/162) for this change.

**Comment by mlandauer** [comment]
This should be fixed now though we do have a new problem in #1477
