### ISSUE TITLE
Add generalised support for coalitions

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/theyvoteforyou#259]
Allow multiple parties to be grouped into coalitions with a name.
- The coalition name is then displayed alongside the party name
- And the coalition is used to determine the whip. So, it is assumed that the parties always vote together

This ticket replaces #15 and #35

**Comment by henare** [comment]
Here's an interesting case study: [we show](https://theyvoteforyou.org.au/divisions/senate/2015-03-18/2) 1 rebellion when [there's really](http://www.abc.net.au/news/2015-03-20/nationals-cross-floor-to-send-message-to-coalition-counterparts/6334014) 4.

**Comment by equivalentideas** [comment]
Another case study http://www.theguardian.com/australia-news/2015/sep/15/nationals-senators-cross-floor-to-back-greens-on-competition-law-changes and here's the division with 0 rebellions https://theyvoteforyou.org.au/divisions/senate/2015-09-15/1
