### ISSUE TITLE
Make photos of people square

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/theyvoteforyou#316]
It's the way everyone is going and it's more flexible from a design point of view. Also we can use circles rather than square avatars

**Comment by tvqt** [comment]
I could potentially do this, as @mlandauer described, with Thumbor, using it locally on the current parliamentarian photos, however, it might be useful to have something that is more futureproof (e.g. something hosted?). 

Is there currently a protocol around photos, keeping things up to date, adding new parliamentarians etc.? Is it a manual or automatic process?

**Comment by mlandauer** [comment]
I don't know if this really belongs here but it would be also great to remove the confusing and distracting colored backgrounds from the images too. They relate to the house that they're in rather than party
