### ISSUE TITLE
Images for policies

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/theyvoteforyou#370]
I'm just going to throw this idea out there and see what happens.

When looking at a person and seeing a long list of policies it looks overwhelming and dry. What if policies had little images that represented them? The idea here is what could represent the policy in such a way that makes it tangible and real and clearly connected to real peoples' lives.

It could see easily be cheesy and horrible and partisan too. There are so many ways it could go badly wrong...

**Comment by mlandauer** [comment]
Still feels like an idea worth exploring. It's likely to not work in so many ways but it feels wrong not to try

**Comment by katska** [comment]
I think there are a few places where visual communication is needed to help distill or bring focus.
