### ISSUE TITLE
Some divisions that require an absolutely majority are incorrectly marked as passed

### ISSUE THREAD

**Issue by henare** [openaustralia/theyvoteforyou#473]
In some situations an [absolute majority is required](http://www.aph.gov.au/about_parliament/house_of_representatives/powers_practice_and_procedure/~/link.aspx?_id=9401351F60524BBF93050639FBA28300&_z=z#abs) to pass a motion.

We don't currently detect this and so we sometimes show a division as having been passed when in fact it failed, e.g. http://publicwhip-rails.openaustraliafoundation.org.au/divisions/representatives/2013-03-21/2

**Comment by mlandauer** [comment]
From #1286 another specific example is https://theyvoteforyou.org.au/divisions/representatives/2021-11-25/2
