### ISSUE TITLE
Add optional comments on editing policy text and votes on policies

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/theyvoteforyou#490]
And attach this to the history. This should work much like a commit message (and edit messages in Wikipedia). It gives people the opportunity to say why they are making a change. It gives more weight to the change made otherwise it might seem arbitrary.

**Comment by mlandauer** [comment]
This still seems worthwhile

**Comment by mlandauer** [comment]
Given the recent interest in the site and that people are starting to really look under the hood how things work and the specific decisions that are made I think adding this feature is now a priority. The need for comments around vote attachment on policies is particularly crucial

**Comment by mlandauer** [comment]
I still think adding this is really important because it will help people understand why the nittty gritty changes are being made. However, I don't think it's worthwhile trying to do this specifically for any interest around election time because the vast majority of the edits made will not have that history. So, it will only become useful over an extended period of time.

**Comment by katska** [comment]
My dumb-ass suggestion here:  that we use github to track changes? Then we have an audit trail we could mine later.

**Comment by mlandauer** [comment]
> My dumb-ass suggestion here: that we use github to track changes? Then we have an audit trail we could mine later.

We're already storing versions in the database. We need it in the database so we can show it when people want to see a policy or division edit history. I don't think there's any particular advantage to putting it in github as well. It certainly wouldn't give us any functionality for free that we need for the application. :-(
