### ISSUE TITLE
Add featured policy to homepage

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/theyvoteforyou#650]
As suggested in #629

**Comment by mlandauer** [comment]
Still seems like a worthwhile idea I think as long as it doesn't make stuff messy

**Comment by katska** [comment]
I'm unclear if this is useful @mlandauer is there any more context that would help me understand?

**Comment by katska** [comment]
@mlandauer @mackaymackay hmm what do you think? Is this still worthwhile?
