### ISSUE TITLE
show policy votes date range

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/theyvoteforyou#662]
It would be helpful to show the date ranges current covered by the policy divisions.

> 7 Divisions, July 2009–May 2013

This might be a useful helper.

**Comment by mlandauer** [comment]
On reflection I don't think this is particularly helpful. It doesn't really tell me whether the policy is particularly current. It maybe says whether it's been voted on recently. I just don't see this is useful. Or am I missing something?

**Comment by katska** [comment]
If I knew there had been another vote on a related matter, I would be able to see if it had been added to the policy yet.

**Comment by mlandauer** [comment]
@katska you can also see this by looking at the date the policy was last edited I think

**Comment by katska** [comment]
I still think the dates a policy has had votes related to it is highly relevant and sensitive as a reflection of someone's position on a policy. Whether it's a priority given other work to do is another question.
