### ISSUE TITLE
Use full name of State instead of abbreviation

### ISSUE THREAD

**Issue by henare** [openaustralia/theyvoteforyou#697]
We have enough room to say "South Australia", e.g. http://publicwhip-rails.openaustraliafoundation.org.au/members/senate/sa/nick_xenophon

**Comment by uma-1602** [comment]
Hey! @henare. I would like to take up this issue. Please guide me how to proceed.

**Comment by equivalentideas** [comment]
Thanks @uma-1602 :) do you have any specific questions about how to implement this?

**Comment by uma-1602** [comment]
Yes @equivalentideas , Thanks a lot. Since I am a beginner, it would be great if you  could help with the file name or path where I can proceed to and fix the issue.

**Comment by equivalentideas** [comment]
@uma-1602 because this issue may involve extracting a helper method, or changing a method on the Member model and writing tests, I think it might be a bit more complex than it sounds :) If that sounds a bit daunting, it's probably a good idea to find another issue to start with.
