### ISSUE TITLE
add acronyms use to style guide

### ISSUE THREAD

**Issue by kat** [openaustralia/theyvoteforyou#744]
Always use an expanded version of any acronyms used in the title and/or description of a policy. Only use acronyms in a title if there is no other way to describe the term and if it is reasonable to assume anyone in Australia would know what it means.

**Comment by katska** [comment]
Those acronyms that are used by small groups of people such as politicians and people associated with them can obscure the meanings of the acronyms and remove our relationship with the meaning of the thing that the acronym stands for. It's one of the main reasons I often oppose their use, even when it's a bit longwinded. 

ARENA is a great example @Mackay. An alternative to defaulting to an acronym can be to use another descriptive shorter number of words. Mixing metaphors and environments here, I'm thinking of contracts where the name of a party is stated and then in brackets how they're then going to be referred to. 

Somewhere in sense making we need to make the invisible, visible first; stop eyes gliding/glazing over the acronyms!

Thoughts on this are invited and encouraged!
