### ISSUE TITLE
What does "whilst Australian Labor Party" mean?

### ISSUE THREAD

**Issue by mithro** [openaustralia/theyvoteforyou#878]
Seen at the bottom of the following page https://theyvoteforyou.org.au/people/representatives/sydney/tanya_plibersek in the `Possible Friends` section.

```
Agreement   Name    Electorate  Party
100%    Harry Jenkins   Scullin whilst Australian Labor Party
```

**Comment by mlandauer** [comment]
I think this problem will just go away when we compare people rather than members.
