### ISSUE TITLE
Incorrect whip possible_votes calculations

### ISSUE THREAD

**Issue by henare** [openaustralia/theyvoteforyou#899]
It says zero possible votes when there was one. From production:

`=> #<Whip division_id: 1387, party: "PRES", aye_votes: 1, aye_tells: 0, no_votes: 0, no_tells: 0, both_votes: 0, abstention_votes: 0, possible_votes: 0, whip_guess: "none", id: 9404, created_at: nil, updated_at: nil>`

Found while fixing #892.

**Comment by mlandauer** [comment]
Related possibly to #1202 which is another problem that is happening in production related to the cache tables
