### ISSUE TITLE
Republish simplified and linkable "Making decisions" infosheet

### ISSUE THREAD

**Issue by henare** [openaustralia/theyvoteforyou#914]
This is really helpful in describing how divisions work but you can't link to specific sections! http://www.aph.gov.au/About_Parliament/House_of_Representatives/Powers_practice_and_procedure/00_-_Infosheets/Infosheet_14_-_Making_decisions_-_debate_and_division

I wanted to link to the "Cutting debate short" section about "the Member be no longer heard" because that's a common division reason. How about we start distilling these things into a glossary or something?

**Comment by mlandauer** [comment]
@mackaymackay would this be useful to include on the site. In the division summary you often repeat an explanation but would it make sense to put this somewhere else so you didn't have to repeat it again and again?
