### ISSUE TITLE
Markdown preview can be different to outputted result

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#932]
e.g. with bullet points you need to have a blank line or else they don't show up but in preview they do even if you don't have a blank line.

https://theyvoteforyou.org.au/divisions/senate/2014-10-28/5

**Comment by equivalentideas** [comment]
Just had this reoccur on https://theyvoteforyou.org.au/divisions/senate/2015-02-12/3

Preview version:

![screen shot 2015-02-13 at 12 14 52 pm](https://cloud.githubusercontent.com/assets/1239550/6180513/1bc058a8-b37a-11e4-96c8-30eab29b5e57.png)

Show version:

![screen shot 2015-02-13 at 12 15 00 pm](https://cloud.githubusercontent.com/assets/1239550/6180515/2113d67c-b37a-11e4-8c6a-8a7997c4d3b4.png)

**Comment by equivalentideas** [comment]
I fixed this by changing adding an extra line before the <ul>. Changed from:

```
> (b) the Senate not accept a public interest immunity claim by the Minister that tabling these documents would impact the Government's ability to properly respond to the Mental Health review because:
> * (i) the production of these documents is necessary to allow people living with mental illness, their representative organisations and service providers to have an open and honest conversation about the future of the mental health system in Australia,
> * (ii) the Mental Health review must be transparent for the community to have faith in the review outcomes,
> * (iii) there has been significant demand from the mental health sector for the reports to be made available to allow for an informed debate in the lead up to Government decision making around the 2015 16 Budget, and
> * (iv) the more than 1,800 organisations and individuals that made submissions to the review have the right to see these reports.
```

to 

```
> (b) the Senate not accept a public interest immunity claim by the Minister that tabling these documents would impact the Government's ability to properly respond to the Mental Health review because:
> 
> * (i) the production of these documents is necessary to allow people living with mental illness, their representative organisations and service providers to have an open and honest conversation about the future of the mental health system in Australia,
> * (ii) the Mental Health review must be transparent for the community to have faith in the review outcomes,
> * (iii) there has been significant demand from the mental health sector for the reports to be made available to allow for an informed debate in the lead up to Government decision making around the 2015 16 Budget, and
> * (iv) the more than 1,800 organisations and individuals that made submissions to the review have the right to see these reports.
```

**Comment by mlandauer** [comment]
The underlying problem is that there is now markdown standard. So, different parsers interpret things a little differently. The preview uses a markdown parser for js while the rails app is obviously using a different one.

There might well be things we could do to tweak this but it might be a case of diminishing returns...

**Comment by henare** [comment]
I think our Rails one isn't doing a good job right now. I don't see why this shouldn't render right (putting it here to test GitHub's render, which I think is open source (and we're using it?)):

> (b) the Senate not accept a public interest immunity claim by the Minister that tabling these documents would impact the Government's ability to properly respond to the Mental Health review because:
> * (i) the production of these documents is necessary to allow people living with mental illness, their representative organisations and service providers to have an open and honest conversation about the future of the mental health system in Australia,
> * (ii) the Mental Health review must be transparent for the community to have faith in the review outcomes,
> * (iii) there has been significant demand from the mental health sector for the reports to be made available to allow for an informed debate in the lead up to Government decision making around the 2015 16 Budget, and
> * (iv) the more than 1,800 organisations and individuals that made submissions to the review have the right to see these reports.

**Comment by equivalentideas** [comment]
Maybe we should look out for parsers using CommonMark http://commonmark.org/

**Comment by mlandauer** [comment]
Ooh I don't like the sound of this bug. It would be good to fix it
