### ISSUE TITLE
Make a glossary for common motions

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#936]
The glossary would translate parliamentary jargon into plain English:

e.g. 'Read a second time' = 'Agree with the main idea of the bill'

Hopefully this will make it easier for people to get involved with editing divisions!

**Comment by equivalentideas** [comment]
Trying to edit [a division](https://theyvoteforyou.org.au/divisions/representatives/2015-02-09/1/), I thought 'Suspension of standing and sessional orders would be a great one to add. It's very confusing insider jargon.

**Comment by katska** [comment]
@mackaymackay any further thoughts on this wording in the current context? Would you change anything to make it clearer?

**Comment by katska** [comment]
Could
"Put the question" be "stop this debate, ask the question and vote now"?

**Comment by mackaymackay** [comment]
@katska I'm happy with these. Improvement is always possible, but I think these do the job is plain language.

**Comment by katska** [comment]
@mackaymackay agreed!
